spring.application.name=Ceylon-Batik

# --- MongoDB Atlas (cloud) ---
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

spring.web.resources.static-locations=classpath:/static/,classpath:/templates/