spring.application.name=Ceylon-Batik
<<<<<<< HEAD

# --- MongoDB Atlas (cloud) ---
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

spring.web.resources.static-locations=classpath:/static/,classpath:/templates/
=======
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.SecurityAutoConfiguration,org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration,org.springframework.boot.security.autoconfigure.web.servlet.SecurityFilterAutoConfiguration,org.springframework.boot.security.autoconfigure.web.servlet.ServletWebSecurityAutoConfiguration
spring.web.resources.static-locations=classpath:/static/,classpath:/templates/
>>>>>>> ac9d41ca05ba4f47616a845828a16c961401d343
